---
name: RHEL for Edge test on RHEL 9

on:
  # Triggered by osbuild-composer CI from gitlab
  repository_dispatch:
    types: [osbuild-composer-ci]

jobs:
  pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number from string PR-xxxx
        id: pr-num
        run: |
          PR_NUM=$(echo "${{ github.event.client_payload.pr_number }}" | cut -d'-' -f 2)
          echo "pr_number=$PR_NUM" >> $GITHUB_OUTPUT

      - name: Get information for osbuild-composer pull request
        uses: octokit/request-action@v2.x
        id: pr-api
        with:
          route: GET /repos/osbuild/osbuild-composer/pulls/${{ steps.pr-num.outputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

    outputs:
      sha: ${{ fromJson(steps.pr-api.outputs.data).head.sha }}
      ref: ${{ fromJson(steps.pr-api.outputs.data).head.ref }}
      repo_url: ${{ fromJson(steps.pr-api.outputs.data).head.repo.html_url }}

  edge-rhel-95:
    needs: pr-info
    runs-on: ubuntu-latest
    # env:
    #   commit_number: ${{ needs.pr-info.outputs.sha }}

    steps:
      - name: Run the tests
        uses: sclorg/testing-farm-as-github-action@v2
        with:
          compose: RHEL-9.5.0-Nightly
          arch: x86_64
          api_key: ${{ secrets.TF_API_KEY }}
          git_url: ${{ needs.pr-info.outputs.repo_url }}
          git_ref: ${{ needs.pr-info.outputs.ref }}
          github_token: ${{ secrets.PAT }}
          update_pull_request_status: true
          tmt_context: "arch=x86_64;distro=rhel-9-5"
          pull_request_status_name: "edge-rhel-9.5"
          tmt_plan_regex: edge
          tf_scope: private
          secrets: "DOWNLOAD_NODE=${{ secrets.DOWNLOAD_NODE }};V2_QUAY_PASSWORD=${{ secrets.V2_QUAY_PASSWORD }};V2_QUAY_USERNAME=${{ secrets.V2_QUAY_USERNAME }};AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }};AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }};GOVC_URL=${{ secrets.GOVC_URL }};GOVC_USERNAME=${{ secrets.GOVC_USERNAME }};GOVC_PASSWORD=${{ secrets.GOVC_PASSWORD }}"
          variables: "ARCH=x86_64;AWS_DEFAULT_REGION=us-east-1;GOVC_INSECURE=1;EDGE_USER_PASSWORD=foobar;CI=true;GIT_COMMIT=12345"
