---
name: Check PR information

# on:
#   repository_dispatch:
#     types: [osbuild-composer-ci]

jobs:
  pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number from string PR-xxxx
        id: pr-num
        run: |
          PR_NUM=$(echo "${{ github.event.client_payload.pr_number }}" | cut -d'-' -f 2)
          echo "pr_number=$PR_NUM" >> $GITHUB_OUTPUT

      - name: Get information for osbuild-composer pull request
        uses: octokit/request-action@v2.x
        id: pr-api
        with:
          route: GET /repos/osbuild/osbuild-composer/pulls/${{ steps.pr-num.outputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

    outputs:
      sha: ${{ fromJson(steps.pr-api.outputs.data).head.sha }}
      ref: ${{ fromJson(steps.pr-api.outputs.data).head.ref }}
      repo_url: ${{ fromJson(steps.pr-api.outputs.data).head.repo.html_url }}
      sender_repo: ${{ fromJson(steps.pr-api.outputs.data).head.repo.full_name }}

  check-outputs:
    needs: pr-info
    runs-on: ubuntu-latest

    steps:
      - name: check outputs
        id: check-output
        run: |
          echo "sha is: ${{ needs.pr-info.outputs.sha }}"
          echo "ref is: ${{ needs.pr-info.outputs.ref }}"
          echo "repo_url is: ${{ needs.pr-info.outputs.repo_url }}"
          echo "sender_repo is: ${{ needs.pr-info.outputs.sender_repo }}"
